add

diff --git a/.github/workflows/matrix.yaml b/.github/workflows/matrix.yaml
--- a/.github/workflows/matrix.yaml
+++ b/.github/workflows/matrix.yaml
@@ -5,20 +5,27 @@ on:
   push:
 
 jobs:
-  job1:
-    runs-on: ubuntu-latest
-    outputs:
-      matrix: ${{ steps.set-matrix.outputs.matrix }}
-    steps:
-      - id: set-matrix
-        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
-  job2:
-    needs: job1
-    runs-on: ubuntu-latest
+  test:
     strategy:
-      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
+      matrix:
+        value: [ubuntu-latest, large-runner-for-backend-ci]
+    runs-on: ubuntu-latest
     steps:
-      - name: Output
-        run: echo ${{ fromJSON(needs.job1.outputs.matrix) }}
-      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
-      - run: echo "${{ matrix.include }}"
+        - run: echo "Hello, ${{ matrix.value }}"
+        - run: exit 1
+
+  notify-failure:
+    runs-on: ubuntu-latest
+    needs:
+      - test
+    if: ${{ failure() }}
+    steps:
+      - run: echo "Test failed"
+
+  notify-result-failure:
+    runs-on: ubuntu-latest
+    needs:
+      - test
+    if: ${{ always() && needs.test.result == 'failure' }}
+    steps:
+      - run: echo "Test failed"
